### ISSUE TITLE
Añadir README.md a página inicial

### ISSUE THREAD

**Issue by thewillyhuman** [weso/shumlex#13]
Hola buenas,

No sé si está en los planes de desarrollo del repositorio, pero estaría muy guay tener un readme en la página inicial para poder saber qué hay en el repo, cómo se puede desplegar, cómo se pueden ejecutar los tests y cómo se puede colaborar en el código.

Si no se te ocurre como hacerlo, aquí te dejo una plantilla que está bastante chula: https://gist.github.com/Villanuevand/6386899f70346d4580c723232524d35a

**Comment by ExarcaFidalgo** [comment]
Correcto. Será el siguiente objetivo. Gracias

**Comment by ExarcaFidalgo** [comment]
Finalizada la base.
